name: paganini_wallet
description: ""

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  sentry_flutter: ^9.3.0
  flutter:  
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  internet_connection_checker_plus: ^2.7.2
  google_fonts: ^6.2.1
  top_snackbar_flutter: ^3.3.0
  awesome_dialog: ^3.2.1
  background_task: ^0.2.0+2
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  formz: ^0.8.0
  flutter_secure_storage: ^9.2.4
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  get: ^4.7.2
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.4
  persistent_bottom_nav_bar: ^6.2.1
  icons_flutter: ^0.0.5

dev_dependencies:
  sentry_dart_plugin: ^3.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/img/
    - assets/splash/
    - assets/svg/
    - assets/lottie/
  uses-material-design: true

flutter_native_splash:
  color: "#9266FB"
  image: assets/splash/logo.png
  android_gravity: center
  ios_content_mode: center

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: integradora
